"""Generate the IEEE and thesis companion repositories from the flagship.

WHY THIS EXISTS
---------------
`16.537 m/s` appears in nine places in the flagship. Four hand-maintained repositories would
make divergence a certainty, and this project has already produced two forks of exactly that
kind: the operating point between motor_model.py and sizing.py (now guarded by
_check_operating_point), and the paper figures against the analysis (now regenerated by
paper/make_figures.py). This is the same answer applied a third time.

The companions are OUTPUT. Nothing in them is authored. Every generated file carries a header
saying so and naming the flagship commit it came from. If a companion is ever hand-edited, the
correct response is to delete and regenerate it -- not to reconcile the two copies.

USAGE
    python3 tools/export_companion.py --out ../companions          # both
    python3 tools/export_companion.py --out ../companions --only paper

Then, in each generated directory:
    git init && git add -A && git commit && git remote add origin <url> && git push
or use tools/bootstrap_repos.sh, which does that for all of them.
"""
import argparse
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The shared cross-link block. Byte-identical in all four repositories -- the flagship's copy
# in PROGRAMME.md is the source, and this is checked by tools/check_links.py.
HEADER_ROWS = [
    ("EMOCD", "Flagship — authoritative engineering record, portfolio", ""),
    ("EMOCD-paper", "IEEE companion — manuscript and reproducibility package *(generated)*", "paper"),
    ("EMOCD-thesis", "Thesis companion — university submission *(generated)*", "thesis"),
    ("EMOCD-lab", "Phase II — research, redesign, deliberately unstable", "lab"),
]
OWNER = "aaaaaaaaaaaavm"


def header_table(here):
    """`here` is '', 'paper', 'thesis' or 'lab'."""
    out = ["<!-- PROGRAMME-HEADER-START -->",
           "| Repository | Role | You are here |", "|---|---|---|"]
    for name, role, key in HEADER_ROWS:
        link = f"[{name}](https://github.com/{OWNER}/{name})"
        cell = f"**{link}**" if key == here else link
        out.append(f"| {cell} | {role} | {'←' if key == here else ''} |")
    out.append("<!-- PROGRAMME-HEADER-END -->")
    return "\n".join(out)


def banner(commit, kind):
    return f"""> ## Generated repository — do not edit here
>
> Every file in this repository is generated from the **EMOCD flagship** by
> `tools/export_companion.py`. Nothing here is authored, and any edit made here will be
> destroyed the next time it is regenerated.
>
> **Source:** [{OWNER}/EMOCD](https://github.com/{OWNER}/EMOCD) at commit `{commit}`
> **Found a mistake?** Fix it in the flagship. This repository will pick it up.
>
> The flagship is the authoritative engineering record. Where this repository and the
> flagship disagree, the flagship is right and this copy is stale.

{header_table(kind)}
"""


# path in flagship -> path in companion. Directories copied recursively.
PAPER_MANIFEST = [
    ("paper/paper.tex", "paper/paper.tex"),
    ("paper/IEEEtran.cls", "paper/IEEEtran.cls"),
    ("paper/EMOCD_IEEE_Conference.pdf", "paper/EMOCD_IEEE_Conference.pdf"),
    ("paper/figures", "paper/figures"),
    ("paper/make_figures.py", "paper/make_figures.py"),
    ("analysis", "analysis"),
    ("requirements.txt", "requirements.txt"),
    ("validation", "validation"),
    ("PROVENANCE.md", "PROVENANCE.md"),
    ("BASELINE.md", "BASELINE.md"),
    ("LICENSE", "LICENSE"),
    ("CITATION.cff", "CITATION.cff"),
]

THESIS_MANIFEST = [
    ("paper/paper.tex", "source/paper.tex"),
    ("paper/EMOCD_IEEE_Conference.pdf", "source/EMOCD_IEEE_Conference.pdf"),
    ("paper/figures", "source/figures"),
    ("analysis", "analysis"),
    ("validation", "validation"),
    ("cad", "cad"),
    ("BASELINE.md", "appendix/BASELINE.md"),
    ("OPEN_PROBLEMS.md", "appendix/OPEN_PROBLEMS.md"),
    ("VALIDATION_REPORT.md", "appendix/VALIDATION_REPORT.md"),
    ("PROVENANCE.md", "appendix/PROVENANCE.md"),
    ("CHANGELOG.md", "appendix/CHANGELOG.md"),
    ("HISTORY.md", "appendix/HISTORY.md"),
    ("docs/DECISION_LOG.md", "appendix/DECISION_LOG.md"),
    ("docs/adr", "appendix/adr"),
    ("LICENSE", "LICENSE"),
]

PAPER_README = """# EMOCD — IEEE companion

Reproducibility package for the EMOCD conference paper: manuscript source, figures, the
analysis scripts that produce every number in it, and the validation run sheets.

## Reproducing the paper's numbers

```bash
pip install -r requirements.txt
cd analysis
python3 verify_field.py && python3 mass_properties.py && python3 motor_model.py \\
  && python3 sizing.py && python3 astro.py && python3 cost.py
```

Results land in `analysis/results/*.json`. Every figure regenerates with
`python3 paper/make_figures.py`, which imports the analysis rather than reimplementing it.

## What is not here

The engineering record — decision log, defect ledger, CAD generations, roadmap — lives in the
flagship. This package exists so a reader can reproduce the paper, not so it can replace the
repository the paper came from.

**Read [`PROVENANCE.md`](PROVENANCE.md) before citing anything.** This is a design study at
TRL 2–3 with no hardware, no measurement and no third-party review.
"""

THESIS_README = """# EMOCD — thesis companion

Final-year thesis submission material, generated from the EMOCD flagship.

## Layout

| | |
|---|---|
| `source/` | Manuscript source and figures |
| `analysis/` | The scripts behind every number |
| `validation/` | Acceptance bands, declared before each run |
| `cad/` | Three CAD generations with their defect audit |
| `appendix/` | Baseline, defect ledger, validation report, provenance, decision records |

## University material goes here, not upstream

This is the one generated repository with hand-added content: submission forms, templates,
formatting mandates and viva material are university-specific and do not belong in the
flagship. **Keep them in `university/`, which the exporter never touches.** Everything outside
`university/` is regenerated and will be overwritten.

**Read [`appendix/PROVENANCE.md`](appendix/PROVENANCE.md) first.** Every number in this work
is a model output. Nothing has been built or measured, and the defect ledger in
`appendix/OPEN_PROBLEMS.md` is published deliberately rather than tidied away.
"""


def copy(src, dst):
    s, d = os.path.join(ROOT, src), os.path.join(dst)
    os.makedirs(os.path.dirname(d) or d, exist_ok=True)
    if os.path.isdir(s):
        shutil.copytree(s, d, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns('__pycache__', '*.pyc', 'output'))
    elif os.path.exists(s):
        shutil.copy2(s, d)
    else:
        print(f"    MISSING (skipped): {src}")
        return 0
    return 1


def build(kind, manifest, readme, out_root, commit):
    dest = os.path.join(out_root, f"EMOCD-{kind}")
    if os.path.exists(dest):
        shutil.rmtree(dest)          # regenerate wholesale; never merge into a stale tree
    os.makedirs(dest)
    n = sum(copy(src, os.path.join(dest, rel)) for src, rel in manifest)
    with open(os.path.join(dest, "README.md"), "w") as f:
        f.write(banner(commit, kind) + "\n---\n\n" + readme)
    with open(os.path.join(dest, ".gitignore"), "w") as f:
        f.write("__pycache__/\n*.pyc\n*.aux\n*.log\n*.out\npaper.pdf\n")
    if kind == "thesis":
        os.makedirs(os.path.join(dest, "university"), exist_ok=True)
        with open(os.path.join(dest, "university", "README.md"), "w") as f:
            f.write("# University-specific material\n\n"
                    "**This directory is never touched by `export_companion.py`.** Submission "
                    "forms, templates, formatting mandates and viva material go here.\n\n"
                    "Everything outside this directory is generated and will be overwritten "
                    "on the next export.\n")
    print(f"  EMOCD-{kind}: {n} paths -> {dest}")
    return dest


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="directory to write the companions into")
    ap.add_argument("--only", choices=["paper", "thesis"], help="build just one")
    args = ap.parse_args()

    dirty = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT,
                           capture_output=True, text=True).stdout.strip()
    if dirty:
        print("WARNING: flagship working tree is dirty. The companions will record a commit "
              "that does not match what was copied. Commit first.\n", file=sys.stderr)
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                            capture_output=True, text=True).stdout.strip()

    out_root = os.path.abspath(args.out)
    os.makedirs(out_root, exist_ok=True)
    print(f"generating companions from flagship {commit} into {out_root}")
    if args.only in (None, "paper"):
        build("paper", PAPER_MANIFEST, PAPER_README, out_root, commit)
    if args.only in (None, "thesis"):
        build("thesis", THESIS_MANIFEST, THESIS_README, out_root, commit)
    print("done. These are output -- do not edit them; edit the flagship and re-run.")


if __name__ == "__main__":
    main()
